### PR TITLE
Remove ipfs-cluster, change ownership

### PR DESCRIPTION
**Pull request by expede**
NOTE: target is Daniel's PR #3 

@dholms I have no way of knowing if these changes will work without _actually running them in Terraform._ A look over them would be helpful 🙏 

I'd also like to add some stuff to systemd restart rules, but not really sure where that would go. Any ideas?

### CODE REVIEW

**Comment by expede** [comment]
@dholms is there any way to test this without _actually_ running it against AWS?

**Comment by dholms** [comment]
For terraform code, you can do a dry-run with `terraform plan` instead of `terraform apply`. Since this is the nix code, I don't think there's a way to test this.

Generally what I did when testing nix code, is dial into an instance, update the nix config, and do a nix rebuild. If that worked, then change it in the code and run a deploy across the whole cluster

**Comment by expede** [comment]
Okay, so nothing special here to hook into Terraform! Good to know. I can test NixOS no problem; thanks!

**Review by dholms — APPROVED** [review]
Looks good :+1:

**Pull request merged**
